import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;

public class ItemRepositorySupport {
	private Connection connection;
	
	public ItemRepository createTableAndRepository() throws ClassNotFoundException, SQLException{
		Class.forName("org.hsqldb.jdbcDriver");
		connection = DriverManager.getConnection("jdbc:hsqldb:mem:inventoryDb", "SA", "");
		createTableItem(connection);
		return new JDBCItemRepository(connection);
	}

	private static void createTableItem(Connection connection) throws SQLException {
		StringBuilder createTable = new StringBuilder();
		createTable.append("create table item")
		.append("(id int generated by default as identity primary key, ")
		.append("name varchar(50) NOT NULL, ")
		.append("quantity int NOT NULL,")
		.append("threshold int NOT NULL)");
		connection.createStatement().executeUpdate(createTable.toString());
	}
	
	public void insert(Item item) throws SQLException {
		String insertIntoItem = String.format("insert into item values(identity(), \'%s\', %d, %d)", item.getName(), item.getQuantity(), item.getThreshold());
		connection.createStatement().executeUpdate(insertIntoItem);
	}

	public void cleanTable() throws SQLException{
		connection.createStatement().executeUpdate("delete from item");
	}
	
	public void dropTable() throws SQLException{
		connection.createStatement().executeUpdate("drop table item");
	}
}
